import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

import Layout from '../layout';
import Header from '../components/Header'
import TitleChannel from '../components/TitleChannel';
import SearchChannel from '../components/SearchChannel';

const Home: NextPage = () => {
  return (
    <>
    <Head>
      <title>Online creator meta tags</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <Layout>

      <Header />
      <main className="ui container">
        
       <div className='ui three column grid'>
         
       </div>
        {/* <section className="ui tall stacked segment">
          <h1 className="ui center aligned header">
            Online creator meta tags
          </h1>

          <p>Метатеги (англ. meta tags) — (X)HTML-теги, предназначенные для предоставления структурированных метаданных (дополнительных, сопроводительных) о веб-странице[1].</p>
        </section> */}

        <div className="ui one column stackable grid">

          <section className="column">
            <div className="ui basic segment">
              <TitleChannel channel="Google" icon='/favicon-google.png' />
              <SearchChannel domain='google.com' title="Meta Tags — Preview, Edit and Generate">
                Learn about Next.js in an interactive course with quizzes! Instantly deploy your Next.js site to a public URL with Vercel.
              </SearchChannel>
            </div>
          </section>

          <section className="column">
            
            <div className="ui basic segment">
              <TitleChannel channel="Yandex" icon='/favicon-yandex.png' />
              <SearchChannel domain="yandex.ru" title="как добавить виджеты в яндексе на главной странице">
              Для того, чтобы добавить виджет на главную страницу Яндекса, необходимо сначала перейти в каталог виджетов здесь. Наведя мышкой на картинку с логотипом виджета, появится кнопка "Добавить", нажав по которой откроется главная страница Яндекса с предложением сохранения выбранного виджета или отмены.
              </SearchChannel>
            </div>
          </section>

          <div className="column">
            <div className="ui segment">
              <div className="channel">
                <TitleChannel channel="Yandex" />
                <h2>Learn &rarr;</h2>
                <p>Learn about Next.js in an interactive course with quizzes!</p>
              </div>
            </div>
          </div>
          
          <div className="column">
            <div className="ui segment">
              <div className="channel">
                <TitleChannel channel="Twitter" />
                <h2>Examples &rarr;</h2>
                <p>Discover and deploy boilerplate example Next.js projects.</p>
              </div>
            </div>
          </div>

          <div className="column">
          <div className="column ui segment">
            <TitleChannel channel="Facebook" />
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </div>
          </div>

        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </Layout>
    </>
  )
}

export default Home
