import Head from 'next/head'

import Header from '../components/Header';
import Footer from '../components/Footer';
import TextArea from '../components/Textarea';
import Parser from '../components/Parser';

interface IChildren {
  title?: string,
  children: React.ReactNode;
}

export default function Layout({title, children}: IChildren) {
  return (
    <>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="keywords" content="js" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

    <div className="wrapper">
      <Header />

      <main className='ui container ui three grid'>
        
        <aside className="six wide column">
          <div className="ui small header">METADATA</div>

          <Parser url="http://site.ru/" name="FrontEnd" />

          <TextArea />
        </aside>
        <div className="ten wide column">
          <div className="ui small header">PREVIEW</div>
          {children}
        </div>
      
      </main>
      
      <Footer />

      <style jsx>{`
        .wrapper {
          position: relative;
          height: 100%;
          display: flex;
          flex-direction: column;
          justify-content: space-between
        }
      `}</style>
    </div>

    </>
  )
}